#ifndef SMART_PARKING_SPOT_DEVICE_H
#define SMART_PARKING_SPOT_DEVICE_H

/**
 * @file SmartParkingSpotDevice.h
 * @brief Declares the Smart Parking Spot S1 application controller.
 */

#include <Arduino.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include "ModestIoT/Device.h"
#include "ModestIoT/Button.h"
#include "ModestIoT/UltrasonicSensor.h"
#include "ModestIoT/PassiveInfraredSensor.h"
#include "ModestIoT/ServoMotor.h"
#include "ModestIoT/CharacterLcdDisplay.h"
#include "ModestIoT/Led.h"

/**
 * @brief Application controller for the Smart Parking Spot S1 prototype.
 *
 * The controller uses ModestIoT components as lego blocks and runs the
 * parking logic from a dedicated FreeRTOS task so the Arduino loop remains idle.
 */
class SmartParkingSpotDevice : public Device {
public:
    /**
     * @brief Creates the parking spot controller.
     */
    SmartParkingSpotDevice();

    /**
     * @brief Stops the background task when the device instance is destroyed.
     */
    ~SmartParkingSpotDevice() override;

    /**
     * @brief Initializes the device and starts the control task.
     */
    void begin();

    /**
     * @brief Handles events emitted by the ModestIoT sensors.
     * @param event Event generated by one of the sensors.
     */
    void on(Event event) override;

private:
    enum class ParkingState {
        Free,
        Busy,
        Reserved,
        Overtime
    };

    static constexpr uint32_t CONTROL_PERIOD_IN_MS = 250;
    // Simulated minute used to make the Wokwi demo observable in a short time.
    static constexpr uint32_t SIMULATED_MINUTE_IN_MS = 1000;
    static constexpr uint32_t MAXIMUM_PARKING_TIME_IN_MINUTES = 120;
    static constexpr uint32_t OVERTIME_THRESHOLD_IN_MINUTES = (MAXIMUM_PARKING_TIME_IN_MINUTES * 80) / 100;
    static constexpr uint32_t OVERTIME_BLINK_PERIOD_IN_MS = 500;

    static constexpr float OCCUPIED_DISTANCE_THRESHOLD_IN_CM = 50.0f;
    static constexpr float FREE_DISTANCE_REFERENCE_IN_CM = 300.0f;

    static constexpr uint8_t LCD_COLUMNS = 16;
    static constexpr uint8_t LCD_ROWS = 2;
    static constexpr uint8_t LCD_I2C_ADDRESS = 0x27;

    static constexpr int ULTRASONIC_TRIGGER_PIN = 5;
    static constexpr int ULTRASONIC_ECHO_PIN = 19;
    static constexpr int PIR_PIN = 23;
    static constexpr int RESERVE_BUTTON_PIN = 32;
    static constexpr int SERVO_PIN = 18;
    static constexpr int RGB_RED_PIN = 25;
    static constexpr int RGB_GREEN_PIN = 26;
    static constexpr int RGB_BLUE_PIN = 27;

    static constexpr int BARRIER_DOWN_ANGLE_IN_DEGREES = 0;
    static constexpr int BARRIER_UP_ANGLE_IN_DEGREES = 90;

    static constexpr const char* COMPANY_NAME = "Libelium";
    static constexpr const char* DEVICE_NAME = "Smart Parking Spot S1";
    static constexpr const char* DEVELOPER_NAME = "Ian";

    static void controlTask(void* taskParameters);

    void controlLoop();
    void sampleInputs();
    void refreshState();
    void applyOutputs();
    void renderDisplay();
    void printStartupBanner() const;
    void reportTracking() const;
    const char* stateToText(ParkingState state) const;
    void setRgbState(bool redActive, bool greenActive, bool blueActive);

    Button reserveButton;
    UltrasonicSensor occupancySensor;
    PassiveInfraredSensor motionSensor;
    ServoMotor barrierServo;
    CharacterLcdDisplay display;
    Led redLed;
    Led greenLed;
    Led blueLed;

    TaskHandle_t controlTaskHandle;
    bool started;
    bool reservationActive;
    bool overtimeBlinkVisible;
    unsigned long busyStartTimestamp;
    unsigned long lastBlinkTimestamp;
    float currentDistanceInCentimeters;
    ParkingState currentState;
};

#endif // SMART_PARKING_SPOT_DEVICE_H
